# Generated by Django 3.0.3 on 2020-03-23 06:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=20, null=True)),
                ('aggregate_percentage', models.IntegerField(max_length=2)),
                ('project_details', models.CharField(max_length=1000, null=True)),
                ('publication_details', models.CharField(max_length=1000, null=True)),
                ('eca_details', models.CharField(max_length=1000, null=True)),
                ('university_to_address', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentRequest.department')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
